name: .NET

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Staging ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: DevelopmentEnv
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/DevelopmentEnv
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: StagingEnv
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/StagingEnv
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --verbosity normal
      
      
    
