name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/development
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/development
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --verbosity normal
      
  release:
    name: Create Release
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false  release
