name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/development
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/development
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --verbosity normal
      
  release:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com/oskarkling/CICD_uppgift_1/tree/production
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: RunProgram
      run: dotnet run
